site_name: Connor Partington
site_url: https://connor-partington.github.io/portfolio/
repo_url: https://github.com/Connor-Partington/portfolio
site_description: A site for sharing my portfolio.
site_author: Connor Partington

extra_css:
    - css/extra.css

theme:
  name: gitbook

plugins: []

nav:
  - Portfolio: index.md
  - Case Studies:
    - Autocab SaaS: autocabsaas.md
  - Technical Samples:
    - How I built my site: how-I-built-my-site.md
    - Release notes: release-notes.md
    - Online help: online-help.md
    - Standard Operating Procedure: sop.md
    - API Endpoint: weatherapi.md